language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- pep8 --exclude=tofdata .
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: rP9X6XMxp+upzXmiB+xwSP0SlWMuQ14wqofMJWZXe7+SGfsA6R5mX7DzYdb6+DHRltXs70MYSTKiKA6CwCCAYW5/ubCr4L51UvjgXHhg6xWhPSD84NE/HZwmEsA9E9vP9eyXZ8NSDXuorBtbKFp/mQPahlP8lmxlY6qloOfDs14d73bgXmv4QHLTrXErlfClk6sybCZsJ4T8nExfpHbQxU9atyqsW5y+Tae8ctyDksMzncu/UWVfnxi6RuEML0N9S3ciGuWyy0/ji+aa1EDXs+oktnf58VKS5qVbj9PQmHT++Ate+cXKWf1nts02uJbLrwJpIv3BrSCpeR/c6+aCj7Dxy3DGRVLAfG+b1fEvvN2/5zYta72JGG0gg1jmpvcch5hvxjRn/yADmWS6MHTtxTyrKiz4YPHVSa6omBd1mjeicdMN4iNEQWIZqTbQegoCtWBJ4/Z29V5gJPKltN/g/f4e3JhGcZHN1ZBS607mzOsIewzTOUx/YkTm8BHihqjaz5Yde7wKNEUe+AJNzbqXrYDisOAhfsxebWDZ+ViAlD9mLM8jSx9H3szB3ESYWk6l2hV0UYruKevbxtVFiXeUo6fV8c/0Dpy0V/IEWHGOMjhsSpDduYxBqQN4mbRCl/pptS+puDmJDczVs/ELUkDRilO9t910a2nEBZrGs4b3kZ4=
  app: tofbot
  on:
    repo: tofbot/tofbot
